[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "identity-credentials-get=*, publickey-credentials-get=*, federated-credentials=*"
    Feature-Policy = "identity-credentials-get *; publickey-credentials-get *"
    Referrer-Policy = "origin"
