[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "identity-credentials-get=*, publickey-credentials-get=*, federated-credentials=*, web-authentication=*, otp-credentials=*"
    Feature-Policy = "identity-credentials-get *; publickey-credentials-get *; federated-credentials *"
    Content-Security-Policy = "default-src 'self' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://accounts.google.com https://apis.google.com https://maps.googleapis.com https://maps.gstatic.com https://www.gstatic.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://maps.googleapis.com; font-src 'self' https://fonts.gstatic.com https://maps.gstatic.com; img-src 'self' data: blob: https: https://maps.gstatic.com https://maps.googleapis.com; connect-src 'self' https: wss: data: https://maps.googleapis.com; frame-src 'self' https://accounts.google.com https://www.google.com; object-src 'none'; base-uri 'self';"
    Referrer-Policy = "origin"
    X-Frame-Options = "SAMEORIGIN"
